### ISSUE TITLE
All Uplay games aren't starting

### ISSUE THREAD

**Issue by MechWOLLIer** [GPUOpen-Tools/OCAT#1]
It seems that there is a general bug with all Uplay games and OCAT. As long as OCAT is open and in "Start" mode, not a single Uplay game is loading at all. Most times even the PC hangs. Is just the programm open and OCAT not startet, everything is fine. 

Than it's also possible to start OCAT after the game and the game runs fine. Also OCAT is working in this case, but without the overlay.

**Comment by criticaldany** [comment]
I tried with Uplay, Steam and Origin games, non work, i disabled every overlay option on all 3 platforms and i cant get it to show up the overlay, it records and gives me the log but no overlay.

**Comment by SrgntBallistic** [comment]
I can confirm that many games launched from a DRM application don't work with the OCAT overlay. I have had success with some games though.

Here's a video outlining some of my experience.

https://www.youtube.com/watch?v=Is4DaAUYdNA

**Comment by jarredwalton** [comment]
The OCAT executable DLLInjector32.exe appears to fail (DRM most likely?) and this results in a couple hundred or so instances of DLLInjector32.exe and Conhost.exe in task manager. It totally bogs down the system for a minute or so, but the UPlay game never launches. I have verified this problem with The Division, Far Cry Primal, and Ghost Recon Wildlands.

If it's DRM-related (which seems likely), it would be great if OCAT could fall back to PresentMon functionality and still work -- don't display the FPS overlay, but still allow the use of the hotkey to start/stop logging.

This problem persists in the latest 1.0.0 version of OCAT.

**Comment by Anteru** [comment]
Thanks for the analysis. We'll take a look how to handle this situation better - obviously it shouldn't create hundreds of instances of `DLLInject32.exe`.

**Comment by dbaumeister** [comment]
Seems like the Windows Creator Update fixed this one. Uplay games start again and the recordings are working.
