### ISSUE TITLE
Even bigger problem with Uplay and OCAT 1.0.1

### ISSUE THREAD

**Issue by MechWOLLIer** [GPUOpen-Tools/OCAT#14]
While OCAT 1.0.1 fixed a few problems i had (a big thank you for that!), it's completely impossible for me to benchmark anything on Uplay. While it was possible with the old OCAT to benchmark Uplay without the overlay, with OCAT 1.0.1 nothing happen in any Uplay games i tested. 

If i use the overlay, Uplay games are not starting at all (while a crazy amount of the same processes were started in the background). And without the overlay, the games are starting, but nothing happen when i press F12.

I am on Windows 10 Creators update with an AMD card and the newest driver. 

Edit
Additional information: Benchmarking Uplay games with Present Mon on the same system is working fine.

**Comment by amddb** [comment]
Hey @MechWOLLIer I can't reproduce your issues with Ghost Recon: Wildlands. 
But here is the deal: I could verify the same behavior on Redstone 1 (So before installing the Creators Update), but going to Redstone 2 fixed those issues (https://github.com/GPUOpen-Tools/OCAT/issues/1). Can you tell me on which games you are having troubles with - and maybe send me your log files?

**Comment by MechWOLLIer** [comment]
Hi @amddb 
Sure, no problem! 
I attached Files war Watch Dogs 2 and Ghost Recon Wildlands. Watch Dogs 2 loads normally, but i don't have an overlay. Also, wenn i stop the game, there is no benchmark result.

In Wildlands, the game isn't loading. The logs are getting bigger and bigger and i don't think it would ever end. When i push stop at OCAT, the tool stops and Uplay is crashing.

I also tried Anno 2205 and For Honor. Both games are doing the same things than Watch Dogs 2.


[wildlands.zip](https://github.com/GPUOpen-Tools/OCAT/files/1025416/wildlands.zip)
[Watchdogs2.zip](https://github.com/GPUOpen-Tools/OCAT/files/1025415/Watchdogs2.zip)

**Comment by amddb** [comment]
Thank you very much! 
Can you provide your system setup as well? Just run dxdiag and send me its summary.

**Comment by amddb** [comment]
Ah and one more thing: Can you share your UPlay settings? e.g. If you have the UPlay overlay and/or the UPlay FPS counter enabled? (UPlay > Settings > General)

**Comment by MechWOLLIer** [comment]
DXDiag is attached. 

Uplay FPS is switched off, the overlay is on. But it's the same problem if the overlay is disabled.
[DxDiag.txt](https://github.com/GPUOpen-Tools/OCAT/files/1025466/DxDiag.txt)

**Comment by amddb** [comment]
Thanks, I will investigate it.

**Comment by rys** [comment]
Uplay incompatibility is a known issue with no workarounds at the time of writing.
