### ISSUE TITLE
No logging at all in DX11, but DX12 works

### ISSUE THREAD

**Issue by MechWOLLIer** [GPUOpen-Tools/OCAT#15]
Hi,

i found another bug.
The new OCAT version isn't logging any game i tested as long it's using the DX11 API. In fact, not a single game worked with DX11 and OCAT. I've got the overlay, it says logging, logging finished, but there is no log.

The funny thing is, that it's logging the same games perfectly fine in DX12. For example in Ashes of the Singularity, Deus Ex Mankding Divided and Rise of the Tomb Raider. In all games, i have an overlay but no log in DX11. And no ovaylay, but a log in DX11.

I attached the log files for a test run in Rottr with DX11 and DX12. Also my system configuration. I am using Windows 10 with the Creators update.
[dx11_rottr.zip](https://github.com/GPUOpen-Tools/OCAT/files/1025553/dx11_rottr.zip)
[dx12_rottr.zip](https://github.com/GPUOpen-Tools/OCAT/files/1025555/dx12_rottr.zip)
[DxDiag.txt](https://github.com/GPUOpen-Tools/OCAT/files/1025554/DxDiag.txt)

**Comment by MechWOLLIer** [comment]
Just for you information:
I tried it again with a different system and a new installed Win 10. But it's the same problem. Funnily, sometimes a file is written. But most times not.

**Comment by amddb** [comment]
Hey @MechWOLLIer thanks for your input. Your "sometimes" means sometimes for the same game or sometimes for different games? Do you switch off the capturing in OCAT between those runs or do you keep the OCAT capturing running in the meantime?

**Comment by MechWOLLIer** [comment]
Sometimes for the same game. For Example F1 2016. Sometimes the OCAT log is working and sometimes not. I tried both: Stop the capturing between different runs and keep running. It makes no difference.

**Comment by amddb** [comment]
Are you able to observe some common behaviour? E.g. the recording is always working on the first try after starting the PC and it is not working after that? In general if anything is not working due to some broken DLL injection, signing out of the current user and signing back in resets the system to a healthy state.

**Comment by MechWOLLIer** [comment]
Sadly not...I tried it out again. Restarted the PC, all of a sudden a log file is created. After this, no new file is being created anymore. I loged off and on again, but no new file. I restarted the system again, no new file again. 

The overlay is working all the time and it says "Capture started", "capture ended" and i also see the results. But there is no log file.

**Comment by MechWOLLIer** [comment]
Now it's getting interesting. It seems that this problem only occurs on Nvidia GPUs. I tried the same (on a different system with Win 10 Creators update) with a RX 580 and the logging works fine. While on different Nvidia cards and drivers it's not working.

**Comment by amddb** [comment]
That's indeed interesting. I'll try to reproduce it on a Nvidia GPU then :)

**Comment by rys** [comment]
Game compatibility was much improved in v1.2 and v1.3. If the issue still persists then please open a new issue.
