### ISSUE TITLE
OCAT can't launch

### ISSUE THREAD

**Issue by farkasg75** [GPUOpen-Tools/OCAT#16]
Hi,

I use windows 10 with creator's update, but I can't launch this program.
I investigated the problem in even viewer, the results are:
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2017-05-26T20:04:41.168990700Z" /> 
  <EventRecordID>3815</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>icon-PC</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>OCAT.exe</Data> 
  <Data>1.0.1.43</Data> 
  <Data>59242bb6</Data> 
  <Data>d3d9.dll</Data> 
  <Data>10.0.15063.0</Data> 
  <Data>631de416</Data> 
  <Data>c0000005</Data> 
  <Data>000000000000fd0c</Data> 
  <Data>1b3c</Data> 
  <Data>01d2d65b4f0223b8</Data> 
  <Data>C:\Program Files (x86)\OCAT\OCAT.exe</Data> 
  <Data>C:\WINDOWS\SYSTEM32\d3d9.dll</Data> 
  <Data>32a36a97-12c4-4995-9fcf-29731a8fc9ad</Data> 
  <Data /> 
  <Data /> 
  </EventData>
  </Event>

- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name=".NET Runtime" /> 
  <EventID Qualifiers="0">1026</EventID> 
  <Level>2</Level> 
  <Task>0</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2017-05-26T20:04:41.121238500Z" /> 
  <EventRecordID>3814</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>icon-PC</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>Alkalmazás: OCAT.exe Keretrendszer verziószáma: v4.0.30319 Leírás: A folyamat egy nem kezelt kivétel miatt meg lett szakítva. Kivétel adatai: kivételkód: c0000005, kivétel címe: 00007FF901D8FD0C</Data> 
  </EventData>
  </Event>

Do we have any idea?

Gabor

**Comment by treeckcold57** [comment]
Hi. I've installed Visual Studio 2017, Python 3.61, and Vulkan SDK and then installed OCAT. Still can't launch at all. 

`Log Name:      Application
Source:        Application Error
Date:          6/5/2017 11:38:04
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      DESKTOP-3TUCPK9
Description:
Faulting application name: OCAT.exe, version: 1.0.1.43, time stamp: 0x59242bb6
Faulting module name: d3d9.dll, version: 10.0.15063.0, time stamp: 0x631de416
Exception code: 0xc0000005
Fault offset: 0x000000000000fd0c
Faulting process id: 0x17c8
Faulting application start time: 0x01d2de11b8c4cc68
Faulting application path: C:\Program Files (x86)\OCAT\OCAT.exe
Faulting module path: C:\Windows\SYSTEM32\d3d9.dll
Report Id: 130eaa83-f9ab-4680-bfb4-1b6afcd43b98
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2017-06-05T15:38:04.653020600Z" />
    <EventRecordID>4335</EventRecordID>
    <Channel>Application</Channel>
    <Computer>DESKTOP-3TUCPK9</Computer>
    <Security />
  </System>
  <EventData>
    <Data>OCAT.exe</Data>
    <Data>1.0.1.43</Data>
    <Data>59242bb6</Data>
    <Data>d3d9.dll</Data>
    <Data>10.0.15063.0</Data>
    <Data>631de416</Data>
    <Data>c0000005</Data>
    <Data>000000000000fd0c</Data>
    <Data>17c8</Data>
    <Data>01d2de11b8c4cc68</Data>
    <Data>C:\Program Files (x86)\OCAT\OCAT.exe</Data>
    <Data>C:\Windows\SYSTEM32\d3d9.dll</Data>
    <Data>130eaa83-f9ab-4680-bfb4-1b6afcd43b98</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>`

from event viewer.

How do I fix this?? Thank you.

**Comment by amddb** [comment]
Hey @farkasg75 and @treeckcold57, thanks for your input. 
Could you do me a favor and look if there is a d3d9.dll located in C:\Windows\SYSTEM32\ ?

**Comment by farkasg75** [comment]
Yes... that problem is defeated with the new version of MSI Afterburner.

**Comment by amddb** [comment]
Hey @farkasg75  - That means, you can start OCAT again after you installed the new version of MSI Afterburner?

**Comment by farkasg75** [comment]
Yes... but I have another problem, when I pushed the Start button, the problem has stopped. I try to make a custom build, but I can't do from source,  because some of the files are missing.

**Comment by amddb** [comment]
1. I assume you mean, that OCAT crashes when you press the Start button? 
2. Can you tell me which files are missing?

**Comment by farkasg75** [comment]
1. Yes exactly
2. Ocat.binaries.wxs
Ocat.Documentation.wxs

**Comment by yekrutdloc** [comment]
Regarding the "OCAT can't launch" issue, I had it occur on me on two separat systems recently. The executable would launch but crash instantly, not even launching. For **me** the problem was the settings file. I changed the last three lines to 0 and OCAT launched with no problems.

**Comment by amddb** [comment]
Hey @yekrutdloc is that with version 1.1.0 ? The major change here is, that the overlay now starts immediately after launching OCAT. So I guess you are seeing the same issue as described here: https://github.com/GPUOpen-Tools/OCAT/issues/23

What happens once you try to enable the overlay in the 'Capture' tab?

**Comment by amddb** [comment]
@treeckcold57 is OCAT still crashing for you?

**Comment by yekrutdloc** [comment]
@amddb Yes latest version, 1.1.0.60. Yes Overlay is the problem, trying to enable it crashes OCAT instantly. I can replicate this on two identical systems, one for AMD graphics cards and one for Nvidia cards.

OS: W10, 1703, 15063.296. Gaming mode and all related settings disabled.

Capturing works flawlessly though, even with Doom which I was having issues with on Presentmon.

**Comment by amddb** [comment]
It looks exactly like you are seeing the same issues as described in https://github.com/GPUOpen-Tools/OCAT/issues/23. I am currently working on it :)

**Comment by rys** [comment]
Closing due to issue age. Please create a new issue if you're still experiencing issues with game compatibility.
