### ISSUE TITLE
Pressing "Start" instantly crashes OCAT

### ISSUE THREAD

**Issue by kamild1996** [GPUOpen-Tools/OCAT#17]
Regardless of options chosen in the app, clicking "Start" causes the app to immediatelly crash, showing the "OCAT stopped working" error.
OCAT version 1.0.1.43, running on Windows 10 Pro x64 Build 1703, AMD Crimson 17.5.1 (Radeon RX 480).

**Comment by kamild1996** [comment]
[PresentMonLog.txt](https://github.com/GPUOpen-Tools/OCAT/files/1036507/PresentMonLog.txt)
Here's the only log I was able to find in the documents folder.

**Comment by knasiotis** [comment]
i have the same problem

**Comment by amddb** [comment]
Hey @knasiotis can I get your log files and potentially a DXDiag analysis of your system as well? (Just search for dxdiag in Windows and use the Button "Save All Information...") Maybe I can identify some overlap.

**Comment by Lunious05** [comment]
i've got same issue.

RYZEN 7 1700
RX 480
Windows 10 creators update (build 15063.296)
[DxDiag.txt](https://github.com/GPUOpen-Tools/OCAT/files/1054652/DxDiag.txt)
[PresentMonLog.txt](https://github.com/GPUOpen-Tools/OCAT/files/1054662/PresentMonLog.txt)

and i upload my dxdiag.txt and presentmonlog.txt

**Comment by amddb** [comment]
Thanks @Lunious05 .
Did anyone of you try to use the 1.0.0 release as well? Is it not working, too?

**Comment by kamild1996** [comment]
Here's my [DxDiag.txt](https://github.com/GPUOpen-Tools/OCAT/files/1054696/DxDiag.txt) as well.

**Comment by kamild1996** [comment]
And 1.0.0 doesn't seem to crash.

**Comment by amddb** [comment]
Oh, that's good news then. Can you please delete your PresentMon log and run the 1.0.0 release again?

**Comment by kamild1996** [comment]
Done, here's the log: 
[PresentMonLog.txt](https://github.com/GPUOpen-Tools/OCAT/files/1054710/PresentMonLog.txt)

**Comment by amddb** [comment]
Thanks @kamild1996  I'll give it a look.

**Comment by knasiotis** [comment]
@amddb 
[DxDiag.txt](https://github.com/GPUOpen-Tools/OCAT/files/1054918/DxDiag.txt)

**Comment by farkasg75** [comment]
I have a same problem with 1.0.1... that independent from mobo, gpu, etc. Because i wanna use for testing a lot of gpus.
What kind of softwares be installed, where the program is works properly?

**Comment by rys** [comment]
Closing due to issue age. Please create a new issue if you're still experiencing issues with game compatibility.
