### ISSUE TITLE
Source code?

### ISSUE THREAD

**Issue by mirh** [GPUOpen-Tools/OCAT#2]
The O in OCAT means [open](http://images.anandtech.com/doci/10894/Radeon%20Software%20Crimson%20ReLive%20%5BNDA%20Only%20-%20Confidential%5D%20v6-page-013.jpg), but where is source code?

**Comment by yekrutdloc** [comment]
https://github.com/GPUOpen-Tools/OCAT/releases

The source is available here

**Comment by mirh** [comment]
Mhh.. no.

**Comment by M4RK22** [comment]
It's not available yet. There are readme files only. They will release later.
