### ISSUE TITLE
OCAT crashes World of Warships

### ISSUE THREAD

**Issue by aschereT** [GPUOpen-Tools/OCAT#22]
WoW version 0.6.8.1, OCAT version 1.0.1.43

Specs:
i7-6700HQ
Windows 10 Pro v1703 build 15063.483
RAM 16GB

---------------------------
Critical Error Occurred
---------------------------
Application C:/Games/WoW/worldofwarships.exe crashed 07.26.2017 at 21:45:33

Message:
The BigWorld Client has encountered an unhandled exception and must close (EXCEPTION_ACCESS_VIOLATION : 0xC0000005 @ 0x736BCF50) (Data Execution @ 0x1936445264)

System info:
	OS Name: Windows 8.1 or later
	OS Version: 6.6 
	OS Architecture: x86_64

Memory info:
	Virtual memory: 2206148Kb/4194176Kb (53%)
	Working set (process physical memory): 1670324Kb/4194176Kb (39%)
	Commit charge (working set + process page file usage): 1867116Kb/4194176Kb (44%)
	Global physical memory: 7875824Kb/16658052Kb (47%)
	Global commitable memory (physical + pagefile): 10074136Kb/16658052Kb (61%)

The application must exit.

---------------------------
OK   
---------------------------

[worldofwarships-2017-07-26_21-45-33.txt](https://github.com/GPUOpen-Tools/OCAT/files/1178840/worldofwarships-2017-07-26_21-45-33.txt)

**Comment by amddb** [comment]
Hey @aschereT , can you tell me a little bit more when that crash happens? Is that during the login screen, when starting the game or at some point while playing the game?

**Comment by aschereT** [comment]
It's after clicking "Play" on the launcher. A black window would show up, but then the game would crash with the given error. When OCAT is closed it would launch normally. I assume it's something to do with the DLL injection?

**Comment by amddb** [comment]
Yes, that's most likely due to the DLLInjection - but crashing the game should not happen in that case. Can you provide the OCAT logs, please? (They are located in Documents/OCAT/Logs).

**Comment by rys** [comment]
Closing due to issue age. Please create a new issue if you're still experiencing issues with game compatibility.
