### ISSUE TITLE
(v1.1.0.60) Single csv made when recording All Processes

### ISSUE THREAD

**Issue by GuestJim** [GPUOpen-Tools/OCAT#25]
In the newly release version 1.1.0.60 if you check "Record performance for all processes" it will record all of the detailed data into a single CSV labelled AllProcesses. Previously the behavior was to create a CSV for each process, with the appropriate label as well, and this is also what is stated in the documentation ([OCAT - Settings](https://ocat.readthedocs.io/en/latest/usage.html#settings)).
Repro steps:

1. on version 1.1.0.60 check **Record performance for all processes**
2. make a recording in a game
3. observe filename and contents of the RecordingResults file generated

Also, I feel this is very important to fix because some games gobble all keyboard inputs, so you have to start a recording outside of the game and come back in, so you need to record all processes to get any data. (Unless you can find a way to always get the input to start to OCAT, which would be amazing.)
Fortunately I have created an R script that will clean up the CSV for me.

**Comment by amddb** [comment]
Hey @GuestJim , in the same manner as with https://github.com/GPUOpen-Tools/OCAT/issues/26: There is no feature in PresentMon that allows to output separate files when recording all processes (that I am aware of). 

I agree with you, that this was quite a useful feature before, but I had to remove these parts in order to keep up with new PresentMon releases --> I just forgot to change that part in the documentation. 

Could you request that feature over at https://github.com/GameTechDev/PresentMon as well? That would be the fastest way to see it in OCAT any time soon.

**Comment by GuestJim** [comment]
Well that's disappointing. At least it was easy enough for me to write an R script to clean up the CSV.
Since these changes were to help keep up with new PresentMon releases, I have a couple quick questions: is it possible to add a field to OCAT for passing command line options to PresentMon (currently it is just the target executable); and is there any way to update PresentMon separately from OCAT, like installing it and setting the path in OCAT or in an environment variable?

**Comment by amddb** [comment]
1. What command line options would you be interested in?
2. It is not that easy, as we do not call the command line options but instead pass the CommandLine struct directly to the respective thread. What you can do though, is to fork OCAT and change the call to PresentMon in PresentMonInterface (or you can change the PresentMon subtree directly with your modified version of PresentMon).

**Comment by GuestJim** [comment]
I don't have special interest in any of the PresentMon command line options, just see it possibly being useful, if there were a way to update PresentMon independently. I could see the delay option being useful for some, including me for those applications that gobble keyboard inputs, so I need to start recording outside the application and then tab back in. Not sure about how much interest there would be in setting the simple, default, or verbose columns (I'm happy with verbose).

**Comment by amddb** [comment]
In that case we can add additional settings to OCAT for delay and logging details.

**Comment by jenatali** [comment]
For what it's worth, I'm totally open to PresentMon refactoring that would make it easier to consume with different backends, if you want to have different CSV formats or filtering or things like that. I'm also open to taking back contributions from OCAT into the PresentMon tree, if you still have the blacklist or multi-CSV code available.

**Comment by amddb** [comment]
Hey @jenatali I am going to prepare some pull-requests for the proposed features. 
I am thinking of adding something like: '-multi_csv' and '-blacklist [path]'. I have to implement that from scratch though, as the previous implementation reported everything back to OCAT which then wrote out the .csv files.

**Comment by GuestJim** [comment]
Looks like the -multi_csv option has been implemented into PresentMon v1.3.0, which was released a few days ago. Hopefully it will not take too much time to bring about OCAT support. (Still rocking my R scripts though, so I'm good for now.)
