### ISSUE TITLE
(v1.1.0.60) Location of FPS showing 

### ISSUE THREAD

**Issue by raven02** [GPUOpen-Tools/OCAT#27]
Just wonder is it possible to choose the location of FPS showing , like the left top corner and also disable the ms second show ?

**Comment by amddb** [comment]
I think that would be totally doable :)

**Comment by raven02** [comment]
Thanks . I also recommend this tool to RPCS3 which is  PS3 emulator supporting D3D12 , GL and Vulkan backend.
