### ISSUE TITLE
(1.1.0.60)Crash during startup. Can't open the log file.

### ISSUE THREAD

**Issue by acemod13** [GPUOpen-Tools/OCAT#29]
Every time I try to run OCAT, the program crashes when it tries to open the log file. The weird thing about it is that the app is looking at a folder that possibly can't decipher (maybe because my laptop runs on a Windows 10 laptop with the Greek language pack in use), but if I look at my Documents folder, the correct folder was made already.
![ocat_2017-09-17_02-08-32](https://user-images.githubusercontent.com/10028592/30516660-b9b288fc-9b4d-11e7-8fb2-83b2a96dfd5c.png)

EDIT: Looking the error again, it looks like OCAT doesn't support Unicode characters well enough.

**Comment by rys** [comment]
Fixed by b12a63b834de5345cc13769461ff41a6702277d3
