### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by rdeleonp** [GPUOpen-Tools/OCAT#3]
There are 2 previous opened issues, no responses at the moment.

No source releases.

What gives? Is this project dead?

**Comment by Anteru** [comment]
No, this project is still active and we hope to be sharing updates with the community soon.

**Comment by yekrutdloc** [comment]
@Anteru Sounds great, any eta on when the next update might come? Also, would love it if the "Start" and "Stop" functionality of the application could be mapped to a key like the logging feature, or it should be on as default.

**Comment by Anteru** [comment]
Please open a new issue for the feature request. I'm closing this issue which was about the missing source.
