### ISSUE TITLE
Fall Creators Update and problems in UWP and For Honor

### ISSUE THREAD

**Issue by MechWOLLIer** [GPUOpen-Tools/OCAT#30]
I installed the Fall Creators Update a few days ago and encountered a few problems with OCAT.

In general, the tool is still working fine, the recording and the overlay. But i found two problems that didn't happen before the update.

1. Sometimes, the tool is crashing while recording Forza 7 and Gears of War 4 (so, it seems to be a UWP problem). It's just a standard crash (.exe is not working anymore) and no more hints. But sometimes the tool works fine, it's not crashing all the time. The problem occurs on AMD and Nvidia cards.

2. It's not possible to record anything in For Honor. I don't know if it's just a problem in the game or in all Uplay games (don't have any other Uplay games installed right now). The overlay is disabled, so that can't be the problem. I can start benchmarking in For Honor, but the only thing OCAT is doing is creating a file with the date and "RecordingResults-0" as a name and that's it. The file itself is empty, just the typical PresentMon lines like "Application", "PrtocessID", "Swapchainaddress" etc. are there. That (perhaps!) just happens on Nvidia cards. At least it worked in For Honor one with an AMD card. But i need to do more testing for myself to clarify this.

**Comment by amddb** [comment]
Hey @MechWOLLIer ,

1. Are you sure that the crashes are directly related to OCAT? Are the games crashing without OCAT being active as well? Or are those crashes only while recording the game?
2. I'll try to reproduce it. That will take a while though, I didn't update to the Fall Creators Update yet, and downloading For Honor takes its time as well. But I've pushed a new version of OCAT: https://ci.appveyor.com/api/buildjobs/4ajtb17vw96a3ksw/artifacts/OCAT_1.1.0.65.exe. 
Can you try if your problems persist with that build?

Cheers

**Comment by MechWOLLIer** [comment]
Hi @amddb 

Thanks, i will try the new build asap. But it could take a bit time, quite busy at the moment.

**Comment by MechWOLLIer** [comment]
Hi @amddb 

I'm not sure if that's another Fall Creators Update problem or just a problem with OCAT 1.1.0.65 (because that version isn't official released, i won't open another issue).

But it seems that the 99,0 percentile summary is broken. I did three benchmarks today and while the FPS are right, the percentiles are all wrong.

I uploaded the performance summary and the logs from the games, so it's easy to see.

[Desktop.zip](https://github.com/GPUOpen-Tools/OCAT/files/1413406/Desktop.zip)

**Comment by amddb** [comment]
Hey @MechWOLLIer ,
Thanks for catching this! I grabbed the wrong column for creating the 99th percentile times...

Regarding "For Honor": It seems like the problem is caused by "For Honor" reporting its name with the trade mark unicode character. OCAT and PresentMon report an empty string in that case and skip the recording. Will have to figure out an alternate way to get the process name.

Did 1.0.1.65 fix your random crashes when recording Forza 7 at least?

**Comment by MechWOLLIer** [comment]
I didn't have the time till now for trying out Forza. But i will asap!

**Comment by MechWOLLIer** [comment]
@amddb

Still have to do the testing with Forza (sorry for the delay...), but perhaps that helps with For Honor.
While presentmon also isn't working in For Honor with the -hotkey function, -scroll_toggle works fine.

**Comment by amddb** [comment]
@MechWOLLIer Good tip, thanks. I'll see what makes the difference there.

**Comment by MechWOLLIer** [comment]
Finally, i tried OCAT 1.1.0.65 in Forza 7 and...well, it worked fine. I tried it five or six times and the tool never crashed :)
