### ISSUE TITLE
Error upon ending recording in Battlefield 1, DX12 mode

### ISSUE THREAD

**Issue by eddr** [GPUOpen-Tools/OCAT#31]
1. Works will for DX11 mode
2. Seems to happen especially for higher resolutions (4K), but happened for 1080p too
3. Other DX12 games are being recorded

Windows 10 1709 build, latest Nvidia drivers

I'll be glad to provide information

**Comment by amddb** [comment]
Hey @eddr, can you give this [version](https://ci.appveyor.com/api/buildjobs/4ajtb17vw96a3ksw/artifacts/OCAT_1.1.0.65.exe) a try, please?

**Comment by aurolou** [comment]
Hey @eddr , I couldn't reproduce the bug with neither the latest [https://ci.appveyor.com/api/buildjobs/e655hjyt1w9mp3rm/artifacts/OCAT_1.1.0.88.exe](version) nor the official release version using the same settings.

**Comment by eddr** [comment]
@amddb works well with the 65 version. Is there a point to test with the release version?
@aurolou Not sure - I do have some other stuff like Nvidia experience installed on the machine. It could interfere maybe.
The 65 version works - do you want me to test with the latest too?

Great stuff - no sure how I missed it before

**Comment by amddb** [comment]
We didn't release a new version yet, these builds are "work in progress" - but glad those work for you :D
No need to test with a later version - except you are curious yourself ;)

**Comment by eddr** [comment]
Wait, I was wrong. It works better (perhaps, not sure), but still has errors:
1. If I change resolution while in game, it results in OCAT overlay not showing and trying to record results in error
2. If I change resolution before I run OCAT -> closes BF1 -> run OCAT -> run BF1, then it works at least for 1440p
3. It doesn't work for 4K. Starts with showing the stats and they disappear as the application loads
4. I should have said that I achieve 4K using Nvidia DSR mode. The display itself is 1080p. I'll test later with a native 4K display + DSR off 
4b. Disabling Nvidia DSR and using 4K via the BF1 game "resolution scaling" option results in the same behavior
5. When I close OCAT, often it will close folders in windows

Tried both 65 and 88 version

**Comment by amddb** [comment]
Regarding 1) Recording shouldn't be affected by the overlay. Can you try to run it with the overlay disabled, please?
5) You can put 'Explorer.exe' onto the OCAT blacklist ("\Documents\OCAT\Config\blackList.txt"). That will prevent OCAT from injecting the overlay.

Will look into the rest next year :)

**Comment by eddr** [comment]
It now works with the overlay disabled + overlay injection option disabled (and I think, only if both)

**Comment by eddr** [comment]
I like the double benchmark files too

Have fun!
