### ISSUE TITLE
OCAT breaks Visual Studio debugging

### ISSUE THREAD

**Issue by Reedbeta** [GPUOpen-Tools/OCAT#32]
While running OCAT 1.1.0.60, I can't launch any programs in the Visual Studio debugger—I get an error popup saying "A 64-bit debugging operation is taking longer than expected. This may be caused by incompatibilities with 3rd party networking software."

As soon as I shut down OCAT, debugging works normally again. However, I've observed that OCAT sometimes crashes on shutdown, and frequently takes down Visual Studio with it.

This is Visual Studio 2015 community edition (version 14.0.25425.01 Update 3), on 64-bit Windows 10, fall creators update (version 1709). My laptop has a Geforce 970M with latest drivers (390.77). Let me know if I can provide any more diagnostic info.

**Comment by amddb** [comment]
Hey @Reedbeta can you try to set Visual Studio (devenv.exe) onto the blacklist ("\Documents\OCAT\Config\blackList.txt") and see if that solves it?

**Comment by Reedbeta** [comment]
@amddb Yes, thanks, adding devenv.exe to the blacklist seems to resolve the issue!

**Comment by amddb** [comment]
I'm glad I could help :)

**Comment by Reedbeta** [comment]
Hmm, actually, I spoke too soon. While putting devenv.exe on the blacklist does resolve the problem with launching the debugger, the OCAT overlay still doesn't appear in my app when debugging, or when launching from Visual Studio (without the debugger) via Ctrl+F5. The overlay _does_ come up if I launch the app from Explorer or the command prompt, though.

Interestingly, I do see a bunch of OCAT output in the VS output view.

	OCAT: 02/12/18 14:02:18	LOG_INFO    12744 VkRender.exe - FileDirectory - OCAT\	C:\Users\Nathan Reed\Documents\OCAT\
	OCAT: 02/12/18 14:02:18	LOG_INFO    12744 VkRender.exe - FileDirectory - Config\	C:\Users\Nathan Reed\Documents\OCAT\Config\
	OCAT: 02/12/18 14:02:18	LOG_INFO    12744 VkRender.exe - BlackList - Blacklist file loaded
	OCAT: 02/12/18 14:02:18	LOG_INFO    12744 VkRender.exe - GameOverlay - Install process hooks for Vulkan
	OCAT: 02/12/18 14:02:18	LOG_INFO    12744 VkRender.exe - FileDirectory - BIN	C:\Program Files (x86)\OCAT\Bin\
	OCAT: 02/12/18 14:02:18	LOG_INFO    12744 VkRender.exe - FileDirectory - Logs\	C:\Users\Nathan Reed\Documents\OCAT\Logs\
	OCAT: 02/12/18 14:02:18	LOG_INFO    GameOverlay64 12744 VkRender.exe - MessageLog - Logging started
	OCAT: 02/12/18 14:02:18	LOG_INFO    GameOverlay64 12744 VkRender.exe - Hook Manager - Install hooks for CreateProcess
	OCAT: 02/12/18 14:02:18	LOG_INFO    GameOverlay64 12744 VkRender.exe - Hook Manager - Successfully installed hook for CreateProcessA
	OCAT: 02/12/18 14:02:18	LOG_INFO    GameOverlay64 12744 VkRender.exe - Hook Manager - Successfully installed hook for CreateProcessW
	OCAT: 02/12/18 14:02:18	LOG_INFO    GameOverlay64 12744 VkRender.exe - GameOverlay - Register module for D3D
	OCAT: 02/12/18 14:02:18	LOG_INFO    GameOverlay64 12744 VkRender.exe - register_module - Register module for C:\WINDOWS\system32\dxgi.dll
	OCAT: 02/12/18 14:02:18	LOG_INFO    GameOverlay64 12744 VkRender.exe - register_module - Successfully installed hook for LoadLibraryA
	OCAT: 02/12/18 14:02:19	LOG_INFO    GameOverlay64 12744 VkRender.exe - register_module - Successfully installed hook for LoadLibraryExA
	OCAT: 02/12/18 14:02:19	LOG_INFO    GameOverlay64 12744 VkRender.exe - register_module - Successfully installed hook for LoadLibraryW
	OCAT: 02/12/18 14:02:19	LOG_INFO    GameOverlay64 12744 VkRender.exe - register_module - Successfully installed hook for LoadLibraryExW
	...
	OCAT: 02/12/18 14:02:20	LOG_INFO    GameOverlay64 12744 VkRender.exe - GameOverlay - Detach because process is terminating

So it does seem that OCAT is hooking this app and it _thinks_ everything is working ok, yet the overlay doesn't actually show up. :confused:
