### ISSUE TITLE
Latest version?

### ISSUE THREAD

**Issue by eddr** [GPUOpen-Tools/OCAT#38]
Hi, is the year old 1.1.0 the latest version? 
Thanks

**Comment by rys** [comment]
@eddr yes, that's the last official release. We're preparing another one to be released soon, in ~2 weeks.

**Comment by eddr** [comment]
Thanks rys! I vaguely remembered a link to some other versions - like this one
 https://ci.appveyor.com/api/buildjobs/e655hjyt1w9mp3rm/artifacts/OCAT_1.1.0.88.exe
