### ISSUE TITLE
FCAT overlay injection

### ISSUE THREAD

**Issue by Woking-34** [GPUOpen-Tools/OCAT#39]
Hi,

Can you make OCAT to support FCAT like color bar overlays for frame time analysis? Thanks!

**Comment by aurolou** [comment]
Hey,

the current [version](https://ci.appveyor.com/api/buildjobs/tl8x8q6grv8im595/artifacts/OCAT_1.1.0.152.exe) shows a red dot in the overlay during recording frame time statistics. Does this serve your needs or which exact feature are you addressing by proposing the FCAT like color bar overlays? :)

**Comment by aurolou** [comment]
Ah, okay. Unfortunately, currently there are no plans to make changes to the overlay. The displayed frame times on the overlay are actually calculated by the delta of the frames, which is independent from the recordings captured by PresentMon, but should appr. the same anyway. For your case, you would need to analyze the overlay text message sequence. Average FPS value is only displayed once the recording has stopped and shows the average FPS from the recording session. If a recording is currently on is indicated by a red dot (would refer to green in the color bar overlay of FCAT), as mentioned in my previous post.
Hope this helps.

**Comment by aurolou** [comment]
I think I got your request now. You are asking for a bar which changes color per frame? I will add it to the list of features we'd consider, but I can't promise anything yet :)

**Comment by aurolou** [comment]
A colored bar sequence is added to the overlay, it's included in the latest versions e.g. [here](https://ci.appveyor.com/api/buildjobs/amt47i8m3w866es5/artifacts/OCAT_1.3.204.exe).
