### ISSUE TITLE
Missing logging for file read/write exceptions

### ISSUE THREAD

**Issue by DevTechProfile** [GPUOpen-Tools/OCAT#45]
If there is a problem with pathes, filenames or anything else the logger doesn't write any entries to find out what is wrong.

**Comment by aurolou** [comment]
This [version](https://ci.appveyor.com/api/buildjobs/owq5e1owdnh8cvtv/artifacts/OCAT_1.2.0.176.exe) writes to the PresentMon log if the capture file could not be created - with the path name in question. If there are any other specific logs you would like to have added please let me know.
