### ISSUE TITLE
Different percentage than just 99th percentile frametimes

### ISSUE THREAD

**Issue by MechWOLLIer** [GPUOpen-Tools/ocat#52]
OCAT is showing the 99th percentile of frametimes in the summary file, which is great.
But i would like the possibility to change the percentage itself. For example, i don't want the 99th percentile, but the 95th percentile. Or the 99,5th or the 99,9th percentile.

Of course it's possible to calculate that number myself, you have all the frametimes in the output file. But i think it would be easier to set a specific number and than get the result in the summary. Would be way more flexible.

**Comment by rys** [comment]
We'll add that to the potential feature list for the next milestone review we do in January!

**Comment by DevTechProfile** [comment]
@MechWOLLIer: You can use CapFrameX: https://github.com/DevTechProfile/CapFrameX
See L-shape curve chart with different p-quantiles.

**Comment by rys** [comment]
@DevTechProfile is there anything you need us to do to inform you if we break compatibility with CapFrameX by changing OCAT’s data output format, or are you happy to just track our `dev` branch?

**Comment by DevTechProfile** [comment]
@rys: No problem. I regularly check your latest version and repository. ^^

**Comment by aurolou** [comment]
Latest [version](https://ci.appveyor.com/api/buildjobs/amt47i8m3w866es5/artifacts/OCAT_1.3.204.exe) adds  95th and 99.9th-percentile to the performance summary report.
