### ISSUE TITLE
OCAT logging isn't working at all in Dirt Rally 2.0

### ISSUE THREAD

**Issue by MechWOLLIer** [GPUOpen-Tools/OCAT#59]
Hi guys,

just tried OCAT in Dirt Rally 2.0 and the tool isn't really working there. While the overlay works fine, the logging isn't working at all. When i press the benchmark button, the tool isn't creating any logging files and isn't even saying that it's recording right now (when you look at the gui). Also, changing the benchmark button isn't helping.

I really use a lot of games with OCAT, but that never happened before. Presentmon meanwhile is working fine, so that's not the problem.

**Comment by aurolou** [comment]
Hey,
seems like Dirt Rally 2.0 is interfering with the keyboard hooks somehow, also the overlay visibility hotkey doesn't work. If you focus a different application, press the capture hotkey and then focus the game again, it should work though. For ending via hotkey, you need to get out of focus again. If you use a delayed start and let it end automatically after a given time, you should be able to get a full capture while the game is in focus.
I will look for the reason why the keyboard hotkey doesn't work when Dirt Rally 2.0 is in focus, but maybe this helps in the meantime as a workaround ...

**Comment by MechWOLLIer** [comment]
Hi,
thanks for the tip, i will try it!
If the Info helps, the hotkey function in presentmon is working.

**Comment by aurolou** [comment]
I changed the hotkey mechanism, this [version](https://ci.appveyor.com/api/buildjobs/ovfih30pmnwm5sf1/artifacts/OCAT_1.3.208.exe) should now also have working hotkeys with Dirt Rally 2.0. However, it does own the key exclusively now.
