### ISSUE TITLE
Huge FPS loss - I just tried OCAT v1.3.0 with some games...

### ISSUE THREAD

**Issue by bosseyes** [GPUOpen-Tools/ocat#60]
and my FPS went down from ~80 to ~50 in Witcher 3 (confirmed with AMD overlay)!!!!!!!
First I thought that upgrading my AMD GPU driver from 19.2.2 to 19.2.3 caused some problems... 
But then I restarted my PC and started Witcher 3 without any other software - Checking the FPS with AMD overlay = ~80 FPS. After that I only started OCAT and restarted Witcher 3 to get the FPS overlay -> ~50 FPS. Then quit OCAT, restart Witcher 3 - back to ~80FPS

So I tried another game (Hitman 1) and got a similar result: from 80-95 FPS without OCAT and 60-67 FPS with OCAT running.

The overlay of OCAT doesn't even have to be active to cause that FPS loss.

That's pretty bad if you ask me.

My specs:
CPU: AMD Ryzen 5 2600 @ Stock
RAM: 16 GB DDR4-3200 CL16
GPU: RX Vega 56 @ Stock
Samsung SSD used @ OS: Win10 (1709)

**Comment by bosseyes** [comment]
wow, I just tried OCAT v1.2.0 and guess what happened? ~25FPS in Witcher 3 wtf...

uninstalled and bye.

**Comment by MechWOLLIer** [comment]
While i can't confirm the FPS loss with the overlay switched off (and the last past for sure isn't helpfull...), i also have the problem that there are some games, where the overlay is reducing the FPS quite a bit. Elex is such i case and i trhink SotTR too (and there are more games). Funnily it's not always the case, also it isn't the problem from day 1 onwards. Possible that this happend with a Win 10 Update, bit i'm not sure.

**Comment by aurolou** [comment]
Hi, thanks for the report. I was able to confirm the FPS drop in Hitman 1 when the overlay was enabled, I will try to check the other games you mentioned as well. Just to be sure ... with "The overlay of OCAT doesn't even have to be active", do you mean the overlay wasn't even enabled within the OCAT UI, or the visibility of the overlay was just toggled off by pressing the hotkey, after the game already started with the overlay enabled? Because while the FPS drop persist also when the overlay visibility is toggled off, I was not able to confirm the FPS drop if the overlay wasn't enabled.
I will investigate the cause of this FPS drop.

**Comment by aurolou** [comment]
This [version](https://ci.appveyor.com/api/buildjobs/sdsfdm9am89wm0f2/artifacts/OCAT_1.3.205.exe) should have less impact on the FPS with enabled overlay, at least for Hitman1. I haven't checked the other games yet. Please note that it includes a frame graph and a colored bar overlay, which seem to drop the fps a bit, too.

**Comment by aurolou** [comment]
I tested the other games, and it seems like the fix helps only for DX11, but not for DX12 yet (Hitman1 as well).

**Comment by aurolou** [comment]
I spend a bit more time on this, please try this [version](https://ci.appveyor.com/api/buildjobs/ovfih30pmnwm5sf1/artifacts/OCAT_1.3.208.exe). I wouldn't say it's completely without any effect, but the fps drop should be greatly reduced, both on DX11 and DX12. Any further feedback welcome.

**Comment by MechWOLLIer** [comment]
I will look into it a bit more next week, but sounds good!

**Comment by aurolou** [comment]
the overlay can now be disabled during performance capture, which should reduce the overhead. if you still experience overhead issues with this new feature (introduced with version 1.6), please open a new ticket
