### ISSUE TITLE
Option to Disable Tones for Start and Stop

### ISSUE THREAD

**Issue by GuestJim** [GPUOpen-Tools/OCAT#62]
Could we get an option to disable the tones when starting and stopping capture?
I definitely see its use and there have been times in the past I wished I had something exactly like this, but I would like it to be an option, for those times I do not want a tone played.

**Comment by aurolou** [comment]
Added with this [version](https://ci.appveyor.com/api/buildjobs/t3vu7m7aeda387rm/artifacts/OCAT_1.4.225.exe).

**Comment by GuestJim** [comment]
Thanks! Very much appreciated.
