### ISSUE TITLE
Hotkeys not working anymore with 1.4

### ISSUE THREAD

**Issue by Taxxor90** [GPUOpen-Tools/OCAT#63]
I've tested the Games Metro Exodus, Kingdom Come and Elex, all work with 1.3.

But only Elex seems to work with 1.4. 
I still get the Overlay in all three games, but with Metro and Kingdom Come neither the recording nor the overlay toggle hotkey is doing anything.

**Comment by aurolou** [comment]
Hi, I will investigate this, thanks for the report. In the meantime my only idea is to try out different hotkeys, if you haven't already done so.

**Comment by Taxxor90** [comment]
Yeah I've already tried that.
In addition, the keys I set in OCAT 1.4 also don't work anywhere else as long as the app is running.

I thought my keyboard was broken, when the "p" key didn't do anything. Then I tried "shift+p", which gave me a "P", so the key itself worked.
Searched a good amount of time before realising that OCAT was the Problem. I set "p" as OSD toggle hotkey.
If I set it to "g", my keyboard doesn't respond to g  anywhere else

**Comment by aurolou** [comment]
yes, that's actually the expected behavior, because it's now using the global windows hotkey approach - which owns the key exclusively. We did the change because on some apps the old hotkey approach wasn't working. Why this method isn't working now on some other games, I need to investigate.

**Comment by MechWOLLIer** [comment]
Just for your information: I have the same problem.
Funnily, it's not the same behaviour on all PCs.
Some Systems i use don't have the problem at all, others have it sometimes, others have it all the time.

Also, it's different from game to game. For example Shadow of the Tomb Raider. With F11, OCAT didn't work at all. Than i changes it to other F-Keys, still not working. Than to "l", it worked fine. But in Kingdom come, l didn't work at all, the same happen with other keys.

I have a similar, but different problem in Hitman 2. OCAT is working fine there, but sometime it's just not starting recording when i press the button. I have to hit it a few times, that it works normal. That's not happening all the time, but regulary.

**Comment by Taxxor90** [comment]
Metro Exodus is another Game me and some others can't bench with 1.4, which was perfectly fine on 1.3

**Comment by MechWOLLIer** [comment]
Looking forward to give this a try, but it will take some time till i can give feedback

**Comment by Taxxor90** [comment]
I can confirm Metro and Kingdom Come are working fine now.

**Comment by aurolou** [comment]
Great, thanks for confirmation.
