### ISSUE TITLE
Option to set key combination as Hotkey

### ISSUE THREAD

**Issue by Taxxor90** [GPUOpen-Tools/OCAT#65]
With the new version blocking every key that is set as a hotkey within OCAT:

Is it possible to let us set something like "ALT+P" or "CTRL+Numpad1" as hotkey just like we can do in the MSI Afterburner and FRAPS?
That way I wouldn't have to close OCAT everytime after I did a capture because I might want to use any of the keys I've set there.

**Comment by aurolou** [comment]
Yes, that's totally possible.

**Comment by aurolou** [comment]
I added the option to require "ALT+_hotkey_". You can try it out with this [version](https://ci.appveyor.com/api/buildjobs/afx9e34xridootm5/artifacts/OCAT_1.4.227.exe).
