### ISSUE TITLE
userBlackList is ignored

### ISSUE THREAD

**Issue by petska** [GPUOpen-Tools/OCAT#69]
userBlackList.txt is ignored by OCAT (latest OCAT_1.4.216.exe)
after adding apps to defaultBlackList.txt ignoring worked correct.
It will be nice to have an option to disable sound completely and the ability to change min/max Y axis values at frametime overlay.

**Comment by aurolou** [comment]
Thanks for the report, I will have a look!

Toggling sound on and off was added in this [version](https://ci.appveyor.com/api/buildjobs/t3vu7m7aeda387rm/artifacts/OCAT_1.4.225.exe), it will be part of the next official release.

Also, I will consider your frametime overlay feature request, but can't make any promises at this point.

**Comment by aurolou** [comment]
This [version](https://ci.appveyor.com/api/buildjobs/ki4nydsq9x4slikg/artifacts/OCAT_1.4.239.exe) should ignore correctly the apps listed in the userBlackList.txt

I opened a new issue (#73) for the frametime overlay request to track it separately.
