### ISSUE TITLE
overlay fails on GTAV

### ISSUE THREAD

**Issue by aurolou** [GPUOpen-Tools/OCAT#79]

**Comment by aurolou** [comment]
A version with a potential fix can be found [here](https://ci.appveyor.com/api/buildjobs/7sby0lg98vrjeo57/artifacts/OCAT_1.5.266.exe).

**Comment by aurolou** [comment]
Fixed with this [version](https://ci.appveyor.com/api/buildjobs/6imnnu89597w2x2h/artifacts/OCAT_1.5.267.exe).

**Comment by TheGoddessInari** [comment]
I just noticed this issue after encountering this several days ago.
The linked build build newly worked on BFV and World of Warcraft, but **isn't** working on [Warframe](https://www.warframe.com/).
Warframe traditionally does work with performance monitors/overlays, though.

**Comment by aurolou** [comment]
Thanks for the report, I will look into Warframe :)

**Comment by aurolou** [comment]
Overlay on Warframe should work with this [version](https://ci.appveyor.com/api/buildjobs/i92dsoexx3ps9d5j/artifacts/OCAT_1.5.268.exe) as well now!
