### ISSUE TITLE
High overhead

### ISSUE THREAD

**Issue by Leadwerks** [GPUOpen-Tools/ocat#90]
This tool puts a significant dent in performance when running. I was trying to use it to record some benchmarking numbers and the framerate dropped from about 1000 to 500 by having this program enabled.

**Comment by aurolou** [comment]
Hi! I would need a bit more information to investigate the problem. Which OCAT version are you running? What are your system specs? On which program did you use OCAT to do benchmarking and what were your OCAT settings? Did you enable the OCAT overlay or just had OCAT running in the background without the overlay hooked into your program?
