### ISSUE TITLE
It must be possible to set install destination

### ISSUE THREAD

**Issue by powerbroker** [GPUOpen-Tools/ocat#92]
Installer asks user for some copyrastic stuff, but doesn't allow to set destination. The destination folder option is much more useful and valuable.

**Comment by aurolou** [comment]
It's already possible to set the destination folder of the installation. When installing, click on Options and set the folder you like.
However, I assume you mean the config and log files? They currently are placed in the Documents folder.

**Comment by powerbroker** [comment]
you're rigt
