### ISSUE TITLE
Overlay not showing for some VULKAN and D3D11 Programs

### ISSUE THREAD

**Issue by 0450** [GPUOpen-Tools/ocat#95]
Programs used were  liblava_2021_alpha lava triangle (VULKAN) and FFXV Benchmark (D3D11). 
Only time the overlay would show on FFXV is when ffxv.exe is launched through OCAT's Launch App instead of the ffxvbench.exe.

[GlobalHook64Log.txt](https://github.com/GPUOpen-Tools/ocat/files/8020241/GlobalHook64Log.txt)
[PresentMonLog.txt](https://github.com/GPUOpen-Tools/ocat/files/8020242/PresentMonLog.txt)
[GameOverlayLog.txt](https://github.com/GPUOpen-Tools/ocat/files/8020243/GameOverlayLog.txt)

**Comment by aurolou** [comment]
FFXV issue with the overlay is a known issue and already listed here: https://ocat.readthedocs.io/en/latest/usage.html#known-issues
The DLL hook is 'too late' to hook into the required functions ... while when launching through OCAT's Launch App, this does not happen. For now, there are no plans to fix this issue as there is a workaround.

I still need to check the laval triangle sample.
